//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeCurrencyServiceTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICaculateService")]
    public interface ICaculateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaculateService/Change", ReplyAction="http://tempuri.org/ICaculateService/ChangeResponse")]
        int Change(int Number, int Ratio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaculateService/Change", ReplyAction="http://tempuri.org/ICaculateService/ChangeResponse")]
        System.Threading.Tasks.Task<int> ChangeAsync(int Number, int Ratio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICaculateServiceChannel : ChangeCurrencyServiceTest.ServiceReference1.ICaculateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaculateServiceClient : System.ServiceModel.ClientBase<ChangeCurrencyServiceTest.ServiceReference1.ICaculateService>, ChangeCurrencyServiceTest.ServiceReference1.ICaculateService {
        
        public CaculateServiceClient() {
        }
        
        public CaculateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaculateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaculateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaculateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Change(int Number, int Ratio) {
            return base.Channel.Change(Number, Ratio);
        }
        
        public System.Threading.Tasks.Task<int> ChangeAsync(int Number, int Ratio) {
            return base.Channel.ChangeAsync(Number, Ratio);
        }
    }
}
